---
# Install Docker
# Base on https://docs.docker.com/engine/install/ubuntu/
- name: Install default packages
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add signing key
  become: true
  ansible.builtin.apt_key:
    state: present
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    state: present
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: Install Docker
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable service docker.service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker.service

- name: Enable service containerd.service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: containerd.service
