---
- name: Configure Device
  hosts: all
  become: True
  tasks:
    # Update package
    - name: update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: upgrade all packages on servers
      ansible.builtin.apt: upgrade=dist force_apt_get=yes

    - name: check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    # Install packages
    - name: install packages for oh my zsh
      ansible.builtin.apt:
        pkg:
          - zsh
          - git
          - htop
          - curl

    # Install Oh My Zsh
    - name: install oh my zsh
      become: false
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ ansible_user }}/.oh-my-zsh"
        depth: 1
        clone: yes
        update: yes

    - name: set default shell for users
      become: true
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: copy zshrc
      become: false
      ansible.builtin.copy:
        src: files/zshrc
        dest: "/home/{{ ansible_user }}/.zshrc"

    # Install transmission
    # source: https://github.com/elboletaire/ansible-transmission
    - name: install transmission
      ansible.builtin.apt:
        pkg:
          - transmission-daemon

    - name: make sure transmission is not running
      service:
        name: transmission-daemon
        state: stopped
      ignore_errors: true
      tags: transmission

    - name: start transmission
      service:
        name: transmission-daemon
        state: started
      ignore_errors: true
      tags: transmission

    # Install ntfs
    - name: install ntfs
      ansible.builtin.apt:
        pkg:
          - fuse
          - ntfs-3g

    # Mount
    - name: create a directory for torrents
      ansible.builtin.file:
        path: /mnt/usb
        state: directory
        mode: "0755"
