---
- name: Configure Device
  hosts: all
  become: true
  tasks:
    # Update package
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - zsh
          - git
          - htop
          - curl
          # NTFS
          - fuse
          - ntfs-3g
          # Transmission
          - transmission-daemon

    # Install Oh My Zsh
    - name: Install Oh My Zsh
      become: false
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ ansible_user }}/.oh-my-zsh"
        depth: 1
        clone: true
        version: 7dcabbe6826073ef6069c8a4b6f9a943f00d2df0

    - name: Set default shell for users
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: "/bin/zsh"

    - name: Copy zshrc
      become: false
      ansible.builtin.copy:
        src: files/zshrc
        dest: "/home/{{ ansible_user }}/.zshrc"
        mode: "0644"

    # External hard drive
    - name: Create a directory for external drive
      ansible.builtin.file:
        path: /mnt/usb_disk
        state: directory
        mode: "0755"

    - name: Mount up device by UUID
      ansible.posix.mount:
        path: /mnt/usb_disk
        boot: true
        src: LABEL={{ usb_volume_label }}
        fstype: ntfs
        opts: defaults,auto,users,rw,nofail,umask=000
        state: mounted

    # Install transmission
    # source: https://github.com/elboletaire/ansible-transmission

    # - name: Make sure transmission is not running
    #   ansible.builtin.service:
    #     name: transmission-daemon
    #     state: stopped
    #   ignore_errors: true
    #   tags: transmission

    # - name: Start transmission
    #   ansible.builtin.service:
    #     name: transmission-daemon
    #     state: started
    #   ignore_errors: true
    #   tags: transmission
